revisionary_main.php

When editing a Revisor edits a post using the "Edit (Classic)" link, the Update button is not recaptioned to "Submit Revision"
Fixes #101

Classic Editor plugin: Update button not recaptioned with Edit (Classic)

---

admin/revision-action_rvy.php

Filter revision data before applying the revision.  All standard post fields (post_content, post_title, etc.) can be filtered.
Fixes #106

New filter: revisionary_apply_revision_data

---

admin/revision-action_rvy.php
readme.txt
revision-creation_rvy.php
revisionary.php
revisionary_main.php

Scheduled revisions could not be published ahead of schedule using "Publish Now" link on preview (since 2.3.4)
Fixes #116

Scheduled revisions could not be published by "Publish Now" preview link

---

revision-creation_rvy.php
revisionary_main.php

This occurred in Revisions Free when a new revision was submitted without changing Featured Image.
Fixes #118

Featured Image removed from revision at creation

---

admin/post-edit-block-ui_rvy.php
admin/rvy_post-block-edit.dev.js

Posts with pending or scheduled revisions stored had misplaced links, bad formatting in Gutenberg editor sidebar

WP 5.5 - Misplaced links in Gutenberg editor sidebar

---

admin/post-edit-block-ui_rvy.php

Revisors and other limited editors have editor elements hidden when adding a new post, under some site configurations.
Fixes #164

Add New Post: suppress revisions JS to avoid invalid editor blockage

---

revisionary_main.php

Gutenberg Ramp allows the block editor to be enabled per-type.  It also supports post-specific control via filter.

Gutenberg Ramp: No revision UI for Gutenberg post types

---

admin/revision-action_rvy.php

The post date should only be updated if the corresponding setting is enabled:
Revisions > Settings > Pending Revisions > Update Publish Date
Revisions > Settings > Scheduled Revisions > Update Publish Date
Fixes #170

Revision publication always updates post date (ignoring plugin setting)

---

admin/class-list-table_rvy.php

Fixes #184  This pertains to Revisors and Contributors under some Permissions configurations.

Revisions not listed in Queue with PublishPress Permissions active

---

admin/rvy_post-block-edit.dev.js

With pre-Publish checks enabled in Gutenberg, after first save "Pending Revision" checkbox is moved off pre-Publish Panel. Fixes #186

With pre-Publish checks, erratic display of "Pending Revision" checkbox

---

admin/rvy_post-block-edit.dev.js

Permissions Pro: redundant Pending Revision checkbox in Gutenberg editor if Status Control module is active with Permissions Pro > 3.3.6
Fixes #188

Permissions Pro: redundant Pending Revision checkbox in Gutenberg

---

admin/class-list-table_rvy.php

PHP Notice "Undefined variable: post_id" when URL includes published_post argument
Fixes #203

Revision Queue: PHP Notice

---

admin/admin_rvy.php

PublishPress Permissions Pro + Status Control: Edit Revision screen had invalid "Workflow" button.  This fix also requires Permissions Pro 3.3.8
Fixes #215

Permissions Pro + Status Control: invalid "Workflow" button

---

admin/history_rvy.php

PublishPress Permissions: Users with Revise permissions for specific pages couldn't compare Pending Revisions.
Fixes #218

PublishPress Permissions: Allow revision compare with Revise permissions

---

revisionary_main.php
rvy_init.php

This changeset also makes function rvy_is_full_editor() accept either on WP_Post object or an integer value (post id) as the $post argument.

lock_others_revisions setting ignored

---

revision-creation_rvy.php

On revision publication, copy all terms from the published post, except for taxonomies that have different selections stored to the revision.  This was previously done only for public taxonomies.
Fixes #77

Polylang Plugin: private taxonomy terms were not stored

---

revisionary_main.php

When comparing past revisions of custom post types, Revisions did not insert the "Preview / Approve" and "Manage" buttons. Fixes #242

Compare Past Revisions: no Preview, Manage buttons for CPTs

---

admin/revision-ui_rvy.php

New filters:
// boolean array with user IDs as array keys
'revisionary_notify_publisher_default_ids'
// array of WP_User objects
'revisionary_notify_publishers_eligible'
Fixes #252

API: Add filter to modify "Publishers to Notify" checkboxes

---

admin/class-list-table_rvy.php

If the Revision Queue was accessed with a filter parameter such as Post Type, Post Status, or Published Post, other filter links were constructed with an encoded ampersand.
Fixes #259

Revision Queue: Filter links had original URL reconstructed incorrectly

---

rvy_init.php

Revision caused corruption of published block content (by slash removal) on some installations.
Fixes #265

Revision submission causes corruption of published block content

---

admin/options.php
rvy_init.php

Pending Revision submission from the Gutenberg editor failed because WP function is_plugin_active() does not exist at REST query handling.
Fixes #287

WP 5.6: Pending Revision submission fails

---

admin/admin_rvy.php

Define a Revisions section for the Capabilities screen. This will currently include edit_others_drafts, edit_others_revisions, list_others_revisions
Fixes #291

PublishPress Capabilities: screen area for Revisions capabilities

---

admin/PostEditSubmitMetabox.php
admin/class-list-table_rvy.php
admin/history_rvy.php
admin/post-edit-block-ui_rvy.php
admin/post-edit_rvy.php
revision-workflow_rvy.php
rvy_init.php

If the 'revisionary_supported_post_types' filter is used to enable revisions for a non-public post type, that post type has ineffective revision preview links.
Suppress the link where appropriate and default rvy_preview_url() output to Compare Revisions screen as a fallback.
Fixes #309

Non-public post types display ineffective preview link

---

rvy_init.php

Restore previous 'init' filter which sets rest_controller_class to defaults, but narrow conditions for this workaround to apply only to Revisions queries.  Also correct implementation to default to WP_REST_Attachments_Controller for post_type 'attachment'

Restore previous REST API Cache compat provision, with modifications

---

admin/filters-admin-ui-item_rvy.php

The Revisions link was disabled due to Compare Revisions issues that are now addressed by other commits.

Classic Editor: No link to Compare Revisions screen for past revisions

---

front_rvy.php

Note: Permissions integration requires 3.5.1

Revisors can't preview other users' pending revisions, even if listed in Revision Queue

---

admin/revision-action_rvy.php
revision-creation_rvy.php
rvy_init.php

Avoid issues with caching plugins by ensuring direct database queries for our postmeta and transients.

Compat precautions: use wrapper functions for all postmeta, transients

---

readme.txt
revisionary.php

This is an accounting consistency release to correspond to wordpress.org. The version 2.5.1 release to the WP svn included incorrect vendor library code (erroneously copied from Revisions Pro).

Release 2.5.2

---

revision-creation_rvy.php

Stop WooCommerce from setting new pending revision Products to Out Of Stock

---

admin/revision-action_rvy.php

Clearance of the post_content_filtered column on revision publication causes data loss in plugins, including Google Web Stories
Fixes #412

post_content_filtered column content lost

---

revision-workflow_rvy.php

New filters allow submission confirmation message to be customized.
Filter array of links with array keys 'preview', 'edit', 'back', 'queue', 'manage' :
* revisionary_submit_message_links
* revisionary_schedule_message_links
Filter full confirmation message string:
* revisionary_submit_message
* revisionary_schedule_message

API: Filters to allow submission confirmation message customization

---

admin/PostEditSubmitMetabox.php
admin/admin-init_rvy.php
admin/admin_rvy.php
admin/filters-admin-ui-item_rvy.php
admin/history_rvy.php
admin/post-edit-block-ui_rvy.php
admin/post-edit_rvy.php
admin/revision-action_rvy.php
admin/revision-ui_rvy.php
admin/revisions.php
front_rvy.php
rest_rvy.php
revision-creation_rvy.php
revision-workflow_rvy.php

This simplifies numerous capability checks, eliminates redundant execution because the WordPress function already:
* Converts $cap->edit_post to 'edit_post' if the post type supports meta capability mapping
* Converts 'edit_post' to $cap->edit_post if the post type does not support meta capability mapping

When checking user's capabilities, pass 'edit_post' not $cap->edit_post

---

admin/admin_rvy.php
admin/class-list-table_rvy.php
revisionary_main.php
rvy_init.php

The following capability is added by default to the Administrator role:
manage_unsubmitted_revisions
Other roles will be unable to see and edit other users' unsubmitted revisions unless this capability is added.

New capability required to see or edit other users' unsubmitted revisions

---

revision-workflow_rvy.php

This corrects issues with sprintf() argument order, but also restructures the message due to awkward phrasing with new "Submitted Revision" terminology.

Email notification: new status labels weren't applied to message appropriately

---

admin/admin_rvy.php
admin/options.php
admin/revisionary.css
admin/settings.js
common/css/pressshack-admin.css

#491
@stevejburge the number of tabs are 9 in free and 10 in pro. Can we merge some sections to reduce the number?
@agapetry didn't tested in pro. Let me know if works fine, in particular displaying license tab and its content as active by default.

Move settings to tabs

---

admin/options.php

Improve captions for capability-related Revisions settings. See #522
Additional clarity will come after Revisions-specific post Capabilities are implemented in the Capabilities UI

Clarity on "requires role capability" settings

---

revisionary_main.php

Fixes #485
Also requires PublishPress Permission fix:
https://github.com/publishpress/PublishPress-Permissions/pull/486

Revisions 3: Exceptions for revision submission don't enable Revision creation

---

admin/class-list-table_rvy.php
admin/options.php
defaults_rvy.php

The manage_unsubmitted_revisions capability was required without any hint in plugin settings; Now not required unless configured in Revisions > Settings

Fix unsubmitted revisions management access control

---

admin/admin-init_rvy.php

This error occured under some undisclosed site conditions.
Fixes #593

Revision Queue: on bulk action, undefined function get_current_screen()

---

admin/class-list-table_rvy.php

Don't apply query string replacement within WPML's CONCAT clause (where it is followed by a closing parenthesis).
Fixes #595

WPML: Database error on Revision Queue screen

---

admin/post-editor-workflow-ui_rvy.php

WP 5.9: Gutenberg editor falls to pieces if Save Draft button clicked after recaption via innerHTML

---

admin/revision-action_rvy.php
revision-workflow_rvy.php

Pass post_type, post_id, revision_id arguments in "revisionary_approval_notify_admin" and "revisionary_submission_notify_admin" filters

API: Additional filter arguments

---

admin/revision-action_rvy.php

WP 5.9: Approval button disabled after revision update

---

admin/revision-action_rvy.php

API: Revision publication does not trigger "wp_after_insert_post" action

---

revisionary.php

In conjunction with the storage of future revisions with "pending" post_status for compatibility with wp-cron publication, also set that status when converting existing future revisions to 3.0 storage format.

Plugin activation: set existing scheduled revisions to "pending" status

---

revisionary.php
revisionary_main.php
rvy_init.php

Fixes #690
Don't give Revisors capabilities for WordPress features that are now represented by private post types.
Also ensure that capabilities are granted for late-registered custom post types.

WP 5.9: Revisors get access to Appearance menu

---

admin/revision-action_rvy.php

Fixes #619
The post date was not updated unless both "Update Publish Date" and "Update Modified Date" are set.

Revision Publication: post date not updated with some plugin settings

---

utils.php

False values passed through the "use_block_editor_for_post" filter did not cause Revisions to detect Classic Editor usage.

Classic Editor not detected based on use_block_editor_for_post filter

---

admin/admin_rvy.php
admin/options.php
admin/revision-action_rvy.php
rvy_init.php

Fixes #771
Also allow usage of alternate scheduled publication method with any WP version.

Scheduled Revision publication fails without explanation if DISABLE_WP_CRON defined

---

rvy_init.php

Alternate template function. WordPress function body_class() is not filterable to include 'home' class for revisions of home page.

pp_revisions_body_class() template function

---

admin/admin_rvy.php
rvy_init.php

Some sites may use wp-cron but handle timed execution with wp-cli / custom code.
Fixes #786

Filter to ignore DISABLE_WP_CRON constant

---

admin/class-list-table_rvy.php

As the screen was narrowed, some of the column header's hidden sorting indicators wrapped down to the next line while others did not.  This caused uneven vertical alignment of the column headers.  Prevent this by suppressing the indicators except to show a current non-standard sort column.

Revision Queue: Don't display column sorting indicator on hover

---

admin/edit-revision-ui_rvy.php

Attempted revision of post expiration settings cause unexpected behavior; disable for now.
Also requires https://github.com/publishpress/PublishPress-Revisions/commit/8968cfff5645b75db89bb66907b3786dc9b50392

PublishPress Future: Prevent revision of unsupported fields

---

admin/class-list-table_rvy.php

Scheduled revisions skipped by WP-Cron are now rescheduled on the next visit to Revision Queue.
To disable auto-reschedule, define constant REVISIONARY_DISABLE_WP_CRON_RESTORATION

Scheduled Revisions missed by WP-Cron were not rescheduled

---

front_rvy.php
revision-workflow_rvy.php

If Revision Submission for Unpublished Posts is disabled but revisions of draft posts were previously created, those caused a "Has Revisions" label without displaying the revisions in Queue
Fixes #902

Has Revisions displayed without any revisions listed in Queue

---

admin/admin_rvy.php
admin/history_rvy.php
admin/options.php
defaults_rvy.php

The revision restore operation affected by this capability check is normally done on the Compare Revisions or Revision Archive screen.

Option to require restore_revisions capability for non-Admins

---

admin/revision-action_rvy.php
revisionary_main.php

When saving currently published content as a past revision at pending / scheduled revision publication, the limit specified by WP_POST_REVISIONS was ignored.

WP-defined limit for past revisions bypassed on revision publication

---

rvy_init-functions.php

If "Limit to one active revision per post" setting is enabled, deleting a revision on a cached site did not restore ability to create a new revision to replace it

Limit to one active revision: acknowledge revision deletion

---

revisionary_main.php

Saving with a future date in Classic Editor saves post as Published instead of Scheduled under some conditions
Fiixes #1155

Classic: scheduled post captioned as published

---

admin/revision-action_rvy.php

PHP Warning on revision submission if published page is child of a trashed parent

---

admin/post-edit-block-ui_rvy.php
admin/rvy_post-block-edit.dev.js

Fixes #1284
Post Editor - "Schedule Revision" button captioning following date selection did not account for time zone difference between site and editing user

"Schedule Revision" button captioning does not account for time zone differences

---

functions.php

Copying this postmeta causes a fatal error for serialization of class Wpil_Model_Link object.
Fixes #1340

Link Whisper plugin: bypass problematic postmeta keys

---

admin/admin-init_rvy.php
admin/admin-posts_rvy.php
admin/class-list-table-archive.php
admin/class-list-table_rvy.php
admin/history_rvy.php
admin/options.php
admin/post-edit-block-ui_rvy.php
admin/post-edit_rvy.php
admin/post-editor-workflow-ui_rvy.php
admin/revision-action_rvy.php
admin/revision-archive_rvy.php
admin/revisions.php
front_rvy.php
includes/CoreAdmin.php
lib/agapetry_wp_core_lib.php
revision-creation_rvy.php
revisionary.php
revisionary_main.php
rvy_init-functions.php
rvy_init.php
submittee_rvy.php
utils.php

Improve wp-admin security by implementing some missing output variable escapes, sanitizations, and nonce checks. For easier security verification, refactor some code to directly output html rather than passing it as a variable. Replace date() and parse_url() calls with recommended WP equivalents. Also remove obsolete commented code.

Security hardening

---

admin/options.php
admin/revisionary.css

Clean up screen space by eliminating one tab and shortening the caption of others. Rearrange some settings and add a few grouping captions for more intuitive discovery and logical association.
Closes #1406

Reorganize plugin settings UI

---

classes/PublishPress/Revisions/Planner.php
classes/PublishPress/Revisions/PlannerCalendar.php
classes/PublishPress/Revisions/PlannerContentBoard.php
classes/PublishPress/Revisions/PluginCompat.php

Modify the handling of the new Revision Statuses on the Calendar, Content Board and Content Overview screens.  They are a completely separate workflow so to avoid clutter and functional chaos, these should generally not be displayed together with normal Posts and Statuses on the same screen. Basically, the "Show Revisions" button functions now function as a toggle between Revisions and regular Posts. Also numerous minor changes including revision preview link with top bar and deletion links because revisions don't yet support trashing.

Improve Planner Integration (Calendar, Content Overview, Content Board)

---

admin/revision-action_rvy.php

Fixes #1454
Also deletes cache of the revision itself, for all caching plugins we currently cater to.

W3 Total Cache: Clean cache after revision publication

---

compat_rvy.php
revision-creation_rvy.php

Revisors can't edit newly created revision if Authors and Permissions plugins both active

---

admin/options.php
uninstall.php

Closes #1156
Note that plugin settings and data will only be deleted if all copies of Revisions and Revisions Pro are deleted (not just deactivated)

Clear Plugin data upon deleting the plugin

---

activation_rvy.php
admin/class-list-table_rvy.php
functions.php
revision-creation_rvy.php
revisionary_main.php

Fixes #1508
Prevent a post from being incorrectly treated as a Revision.

Updating a post can cause post status to be cleared

---

rvy_init-functions.php

Fixes #1534
Skip the display caption if this filter is applied prior to the init action. In that case, the filter application stems from another plugin's premature wp_schedule_event() call and the caption won't actually be used.

PHP Notice in WP 6.8 if another plugin calls wp_schedule_event() too early

---

admin/admin_rvy.php
admin/options.php
common/css/_tooltip.css
common/css/_tooltip.less

Improve clarity and consistency of captions for capability requirement settings. Link to Capabilities tab for capability assignment, with tooltip explanation.
Closes #522

Clarify captions for capability requirement settings

---

admin/admin_rvy.php
admin/options.php
admin/revisionary.css
revisionary_main.php

Don't display Revisions plugin submenus or tabs for a feature that's disabled for all post types.

If Past Revisions or New Revisions are disabled for all post types, suppress menus and tabs

---

revisionary.php

The Composer autoload mechanism does not allow multiple versions of the library to be compared, so execute its include.php manually.

Ensure packaged version of wordpress-version-notices is considered for loading

---

admin/revision-action_rvy.php

Fix handling when wp_revisions_to_keep() returns -1.

Early exits in revision cleanup

---

admin/options.php

Legacy Notifications cannot be enabled if PublishPress Planner is not activated
