admin/admin-init_rvy.php, admin/class-list-table_rvy.php, admin/revision-action_rvy.php, admin/revision-queue_rvy.php
=> Revision Queue: new bulk action to unschedule selected revisions

admin/admin_rvy.php, admin/rvy-revision-edit.css
=> Compat: Public Post Preview - support display on Edit Revision

revisionary_main.php
=> Public Post Preview view attempt fails for non-Administrators

rvy_init.php
=> PHP warning on settings screen

admin/admin_rvy.php, readme.txt, revisionary.php
=> Admin Posts screen: Display post state "Has Revision"

revision-creation_rvy.php, revision-workflow_rvy.php, rvy_init.php
=> WP 5.5 - "Pending Revision" checkbox sometimes ineffective

admin/edit-revision-ui_rvy.php, admin/filters-admin-ui-item_rvy.php
postL10n is no longer defined. Fixes #136
=> WP 5.5 - With Classic Editor, javascript errors in post editor

admin/admin_rvy.php
=> "Has Revision" post state displayed inappropriately for some posts

admin/rvy-revision-edit.css, admin/rvy_revision-block-edit.dev.js
=> WP 5.5 Edit Revision: duplicate preview link, misaligned approve link

admin/revision-action_rvy.php
Since version 2.3.9
Fixes #144
=> Scheduled revisions were not published under some conditions

revisionary_main.php
PublishPress Integration: no notification for Editorial Comments added on "Edit Revision"
Fixes #148
=> PublishPress Integration: Editorial Comment email notification

admin/options.php, admin/revision-action_rvy.php, defaults_rvy.php
=> Option to copy revision's editorial comments to published post

admin/admin_rvy.php, admin/post-edit-block-ui_rvy.php
New filters:
'revisionary_pending_checkbox_caption'
'revisionary_pending_checkbox_caption_classic'
Closes #162
=> API: filtering for Pending Revision checkbox caption

admin/filters-admin-ui-item_rvy.php
=> Preview Changes click recaptions "Submit Revision" button

admin/admin_rvy.php
=> Public Post Preview - Author selector hidden in post editor

front_rvy.php, revisionary_main.php
Public Post Preview plugin: Make previews of published revisions redirect to the published post.
=> Public Post Preview integration: published post redirect

admin/post-edit-block-ui_rvy.php, revision-creation_rvy.php
Support constants REVISIONARY_DISABLE_SUBMISSION_REDIRECT, REVISIONARY_DISABLE_SCHEDULE_REDIRECT
Add filters revisionary_do_submission_redirect, revisionary_do_schedule_redirect
Closes #211
=> Provide a way to disable revision submission redirect

revisionary_main.php
=> Error when Revision submission includes a template setting

admin/history_rvy.php
=> Pro: Error when comparing revisions of an unpublished post

revisionary_main.php
Followup to previously committed changes.
=> Remove a post type object creation (now created earlier)

revisionary_main.php
=> list_others_pages capability should let Revisors see uneditable drafts

revisionary_main.php
Database error on revision submission due to UPDATE ID query
Fixes #231
=> ODBC Database error on Project Nami installations

rvy_init.php
=> Published Post Thumbnail, Page Template cleared on Revision submission

rvy_init.php
Revision submission by a Revisor causes corruption of published block content (by slash removal) on some ACF installations
Fixes #247
=> Revision submission corrupts published blocks on some installations

admin/post-edit-block-ui_rvy.php, admin/post-edit_rvy.php, revision-creation_rvy.php, revisionary_main.php, rvy_init.php
=> WP Engine, Kinsta object cache: "Pending Revision" checkbox ineffective

revisionary_main.php
=> PublishPress Permissions: Revision editing or deletion improperly blocked

rvy_init.php
=> REST API Cache plugin: "Save as Revision" checkbox ineffective

admin/class-list-table_rvy.php
=> Revision Queue: If no revisions accessible to user, all are listed

revision-creation_rvy.php
=> Post deletion triggers revision submission redirect under some conditions

admin/revision-action_rvy.php, revision-creation_rvy.php
=> PublishPress Authors: Revision Creation causes undefined class error

admin/history_rvy.php
This behavior is now modified to display the user who authored the last published update. Fixes #287
=> Compare Pending Revisions credits post author for Current Revision

admin/class-list-table_rvy.php
=> WPML: Language filter not applied to Revision Queue

revision-creation_rvy.php, revisionary_main.php
=> TablePress: Tables could not be updated by non-Administrators

admin/class-list-table_rvy.php
=> Revision Queue: PHP Notice if no revisions listed

rvy_init.php
=> REST API Cache plugin: Error with Media post type

admin/history_rvy.php
=> Compare Revisions: Restore button displayed to user who can't actually restore the revision

admin/admin-init_rvy.php, admin/options.php, admin/revision-action_rvy.php, defaults_rvy.php
=> Hotfix 327 order revisions by modified date

admin/post-edit-block-ui_rvy.php
=> PublishPress: Custom Status module interferes with Edit Revision UI

revision-creation_rvy.php
=> Advanced Custom Fields: attachment image fields cleared from new revision

revisionary_main.php
=> PublishPress: Editorial Comments on Edit Revision broke update process

revision-workflow_rvy.php
=> Scheduled Revision confirmation: Go Back link fails on some sites

rvy_init.php
=> REST API Cache: "Save as Revision" checkbox fails on some installations

admin/revisionary.css
=> Compare Revisions - Uneven column width with WP 5.7

admin/admin_rvy.php, rest-insert_rvy.php, revision-creation_rvy.php, revisionary_main.php, rvy_init.php
=> Kinsta object cache - Revision submission clears Featured Image from published post

rvy_init.php
=> Kinsta object cache: "save as revision" checkbox fails

rvy_init.php
=> Pro support: Divi - save as pending checkbox failed with Classic Editor

admin/post-edit-block-ui_rvy.php
=> PublishPress: Custom Status dropdown hidden in post editor

admin/revision-action_rvy.php, revision-creation_rvy.php
=> Post Title changes not applied at revision publication

admin/admin_rvy.php
=> PublishPress Permissions: Edit Category - Permissions metaboxes not displayed

admin/revision-action_rvy.php, revision-workflow_rvy.php
Fixes #388
Also requires PublishPress Revisions patch: https://github.com/publishpress/PublishPress-Permissions/pull/380
=> PublishPress Permissions: Pending Revision Monitors group ineffective

revisionary_main.php
Improve compatibility with some plugin-defined custom post types.
=> Compat: Enable revisioning of non-public post types with type-specific capabilities

revisionary_main.php
=> Revision submission: prevent error for invalid key under some configurations

admin/revisionary.css
=> Revision Queue: Color links like Edit Posts

rvy_init.php
=> API to prevent postmeta update from deleting other key matches

revisionary_main.php
=> Compat: Custom Permalinks settings cleared on revision publication

revision-creation_rvy.php
=> Scheduled Page Revisions: current page template setting not copied to revision

rvy_init.php
=> Revision Scheduling: Background fatal error on some sites

revisionary_main.php
=> Query filter for Custom Permalinks compat

admin/class-list-table_rvy.php, revisionary_main.php
=> Revisions can become disassociated from main post

revisionary_main.php
=> Permissions integration: Specific Permissions not applied for custom post types

rvy_init.php
=> Prevent revision previews from being cached by browser

revisionary_main.php
=> Previews of front page revisions don't load front page template

admin/post-edit-block-ui_rvy.php
=> API: filter application of 'revisionary_default_pending_revision' ineffective in Gutenberg

front_rvy.php
Add a new action for Pro to hook into
=> Pro API: Revision Previews may not display unmodified custom field data

rvy_init.php
=> Bulk Approval of revisions may fail if post type not registered early enough

front_rvy.php
=> Revision Preview: recaption "List" button to "View Queue"

admin/post-editor-workflow-ui_rvy.php, admin/rvy_revision-block-edit.dev.js, admin/rvy_revision-block-edit.js
=> Gutenberg plugin: generic error screen when submitting revision in 3.0

revisionary_main.php
=> Front Page setting dropdown in Settings > Reading included revisions

revisionary_main.php
=> Revision submission clears WordPress homepage setting

admin/post-editor-workflow-ui_rvy.php, admin/rvy_revision-block-edit.dev.js
=> Scheduled revisions could not be updated in Gutenberg editor

front_rvy.php
=> Revision Preview: No label on Approve button if base post is unpublished

admin/post-editor-workflow-ui_rvy.php, revisionary_main.php
=> Disabling Revision Submission doesn't suppress New Revision functionality

revisionary_main.php
=> Events Calendar plugin: No revision submission in Classic Editor

admin/rvy_revision-classic-edit.dev.js, admin/rvy_revision-classic-edit.js
=> Adapt Classic Editor revisions UI to EC customization of publish metabox

admin/revision-action_rvy.php, functions.php
=> Bulk-deleting revisions does not update revision counts

admin/class-list-table_rvy.php
=> Revision Queue empty on sites with large number of published posts

admin/rvy-revision-edit.css
=> WooCommerce: Revision Editing includes UI for non-revisionable properties

revisionary_main.php
=> New Revision button not displayed in Admin Bar

admin/class-list-table_rvy.php
=> Revision Queue: revisions not listed in My Activity view

admin/admin_rvy.php, admin/options.php
=> Multisite: Network-wide settings not displayed or editable

functions.php, rvy_init.php
=> Published custom post types not listed under some configurations

admin/rvy_revision-block-edit.js
=> Edit Revision: cannot update unless SCRIPT_DEBUG is enabled

front_rvy.php, revisionary-front.css
=> Frontend toolbar design update

admin/class-list-table_rvy.php
Revisions from deactivated post types were listed with invalid Edit, Delete links and a blank Post Type
=> Revision Queue - deactivated post types handling

admin/revision-action_rvy.php
=> Sites running object caching: Revision status change, counts display wrong

rvy_init.php
=> Compare Revisions: Preview button for past revisions links back to Compare screen

admin/history_rvy.php
=> Compare Revisions: error if ACF is active on a PHP 8 installation

admin/class-list-table_rvy.php
=> Revision Queue: bad column header links (to set sort field)

revision-creation_rvy.php
=> Some new revisions not listed in Queue or linked to Preview button

admin/class-list-table_rvy.php, functions.php, revision-creation_rvy.php
=> Store future revisions using "pending" status

revision-creation_rvy.php
=> New revisions created with "Auto-submit" option have wrong date

admin/admin-dashboard_rvy.php, admin/admin_rvy.php, revisionary_main.php
=> Scheduled revisions not included in dashboard Publishing Soon list

utils.php
=> Pro: Divi - Classic Editor setting did not trigger correct Revisions UI

revisionary_main.php
=> Settings > Revision Creation > "Additional role capability required" ignored

admin/class-list-table_rvy.php, revision-creation_rvy.php
=> Revision Queue: "Copy Revision" function

admin/revision-action_rvy.php, rvy_init.php
=> Scheduled Revisions fail on some sites

admin/RevisionEditSubmitMetabox.php, admin/revision-action_rvy.php, revisionary_main.php
=> Non-public Post types have bad revision preview links, revision publication redirects

rvy_init.php
Support constant PP_REVISIONS_NO_POST_KSES
Fixes #724
=> HTML block: html comments corrupted on revision creation / edit

admin/revision-action_rvy.php
=> PublishPress Authors: Revision submission fails

front_rvy.php
=> Pro: Items in Beaver Builder module selector were duplicated

revisionary_main.php
=> Edit New Revision redirect failed under some conditions

revisionary.php
=> WP 6.0: Fatal error loading Customizer

admin/options.php, admin/revision-action_rvy.php, defaults_rvy.php
=> Option to delete editorial comments when a revision is published

admin/admin-init_rvy.php, admin/options.php, revisionary_main.php
=> Settings tab, option checkboxes to disable revision per-type

admin/admin_rvy.php, revisionary.php
=> Add plugin review request

admin/options.php, admin/revisionary.css, includes/CoreAdmin.php
=> Settings screen: Pro promo sidebar

composer.json, revisionary.php
=> Include instance protection library

rvy_init.php
=> Scheduled Revision publication fails if plugin settings have never been updated

revisionary_main.php
=> Updating Scheduled Revision date doesn't change actual publish time

revision-workflow_rvy.php
Notification could fail on sites that pull user data from a non-standard source.
=> Prevent potential email notification failure

admin/admin_rvy.php, rvy_init.php
=> Correct detection of DISABLE_WP_CRON constant

rvy_init.php
=> Yoast SEO: Invalid "indexable" maintenance operation on revision creation / submission

admin/class-list-table_rvy.php
=> Revision Queue column ordering, filtering links fail in some use cases

front_rvy.php
=> Scheduled Revision preview: if published, top bar "Edit" link has invalid URL

revision-workflow_rvy.php
=> No email notification to Administrators under some role configurations

rvy_init.php
=> Revision Notification: invalid preview_id argument in preview url prevents top bar display

revisionary.php
=> If Pro plugin is activated, deactivation of free plugin hides all revisions

admin/admin-init_rvy.php, admin/class-list-table_rvy.php
=> Bulk-deleted revisions are not removed from revision count

revisionary.php
=> If plugin deactivated while Revisions Pro active, revisions become hidden

revision-workflow_rvy.php
=> Quote is not rendered on email notification

admin/admin_rvy.php
=> Plugin review request dismissal is not applied

utils.php
=> PHP Notice when another plugin uses "use_block_editor_for_post" filter

admin/post-edit-block-ui_rvy.php, admin/post-edit_rvy.php, admin/post-editor-workflow-ui_rvy.php, admin/revision-action_rvy.php, admin/rvy_revision-block-edit.dev.js, admin/rvy_revision-block-edit.js, rvy_init.php
=> Submit and approve changes to post author

admin/revisionary.css
=> Post Edit screen: "Visibility" caption crowded

admin/post-edit-block-ui_rvy.php
=> Edit Scheduled Revision: "Immediately" shown as Publish date

admin/post-edit-block-ui_rvy.php, admin/post-edit_rvy.php
=> PHP 8 - Unresponsive elements in post editor due to Javascript loading failure

utils.php
"script tried to modify a property on an incomplete object"
Fixes #856
=> WP Buddy Rich Snippets - PHP error

admin/revision-action_rvy.php
=> Encoded quotation mark in revision approval email notice

admin/admin-init_rvy.php
=> Fatal error on revision approval on some sites

admin/admin_rvy.php
If Relevanssi settings have filtering enabled for admin searches, Submitted / Scheduled Revisions are included in search results.
=> Relevanssi: Submitted / Scheduled Revisions in admin search results

admin/RevisionEditSubmitMetabox.php
New filter "revisionary_submit_revision_metabox_classic"
=> API: Support filtering of revision submission panel in Classic Editor

admin/class-list-table_rvy.php
=> Revision Queue has no "check all" box

admin/admin-init_rvy.php, admin/revision-action_rvy.php
=> Revisions could not be properly declined on some cached sites

front_rvy.php
=> Pro: Revisions previews in Elementor showed inactive buttons in top bar

admin/history_rvy.php, rvy_init.php
=> Compare Revisions: Preview button for past revisions fails

admin/revisions.php
=> Manage Revisions screen: link title html is escaped

rvy_init.php
=> Revision Queue: filtering for a specific post does not show unsubmitted revisions

submittee_rvy.php
=> Network Activation: Setting Scope update fails

composer.json, composer.lock, revisionary.php
=> Require PHP 7.2.5

admin/admin_lib-mu_rvy.php
=> Multisite: Plugin settings UI not displayed

admin/options.php
=> Settings from previous network-wide activation affect single-site settings display

revisionary_main.php
=> Permissions + WordFence: Add Media query not filtered based on Permissions settings

admin/admin-posts_rvy.php, admin/options.php, admin/post-edit-block-ui_rvy.php, admin/post-edit_rvy.php, defaults_rvy.php, revisionary_main.php, rvy_init.php
=> New Feature: limit to one active revision per post

admin/post-edit-block-ui_rvy.php, admin/post-edit_rvy.php
=> Standard Author selection UI is showing when Elementor active

revisionary_main.php
=> Beaver Builder: Redirect loop

admin/admin_rvy.php
=> Admin Dashboard: "At a Glance" improperly filtered

admin/class-list-table_rvy.php
=> Authors: "Revised By" column of Revision Queue shows original Post author

admin/revision-action_rvy.php
=> PublishPress Authors: Author changes not applied at revision publication

admin/class-list-table_rvy.php
Unidentified plugin conflict inserting inappropriate clauses into Revision Queue posts query.
Fixes #996
=> Plugin conflict with Revision Queue posts query

revision-creation_rvy.php
=> Revisions incorrectly attributed to original page author under some conditions

admin/history_rvy.php
=> Compare Revisions: PHP Notice under some conditions

admin/revision-action_rvy.php
=> Unscheduling a revision using bulk edit in Revision Queue makes it inaccessible

dev-workspace/build-push, dev-workspace/docker/Dockerfile, dev-workspace/docker/compose.yaml
This reverts commit 91c0b0b3fe3e23d711ce172bce5447b24651f415.
=> Revert "dev-workspace updates"

lib/vendor/composer/installed.json, lib/vendor/composer/installed.php, lib/vendor/publishpress/instance-protection/LICENSE, lib/vendor/publishpress/instance-protection/core/Autoloader.php, lib/vendor/publishpress/instance-protection/core/Config.php, lib/vendor/publishpress/instance-protection/core/InstanceChecker.php, lib/vendor/publishpress/instance-protection/core/LibState.php, lib/vendor/publishpress/instance-protection/include.php, lib/vendor/publishpress/wordpress-reviews/LICENSE, lib/vendor/publishpress/wordpress-reviews/ReviewsController.php, lib/vendor/publishpress/wordpress-version-notices/includes.php, lib/vendor/publishpress/wordpress-version-notices/license.txt, lib/vendor/publishpress/wordpress-version-notices/src/Autoloader.php, lib/vendor/publishpress/wordpress-version-notices/src/Module/AdInterface.php, lib/vendor/publishpress/wordpress-version-notices/src/Module/MenuLink/Module.php, lib/vendor/publishpress/wordpress-version-notices/src/Module/TopNotice/Module.php, lib/vendor/publishpress/wordpress-version-notices/src/ServicesProvider.php, lib/vendor/publishpress/wordpress-version-notices/src/Template/TemplateInvalidArgumentsException.php, lib/vendor/publishpress/wordpress-version-notices/src/Template/TemplateLoader.php, lib/vendor/publishpress/wordpress-version-notices/src/Template/TemplateLoaderInterface.php, lib/vendor/publishpress/wordpress-version-notices/src/Template/TemplateNotFoundException.php, lib/vendor/publishpress/wordpress-version-notices/src/Versions.php, lib/vendor/publishpress/wordpress-version-notices/src/autoload.php, lib/vendor/publishpress/wordpress-version-notices/src/deprecated.php, lib/vendor/publishpress/wordpress-version-notices/src/include.php, lib/vendor/publishpress/wordpress-version-notices/templates/menu-link/menu-link-script.php, lib/vendor/publishpress/wordpress-version-notices/templates/menu-link/redirect-page.php, lib/vendor/publishpress/wordpress-version-notices/templates/top-notice/notice.php
* Add instance-protection
* Add wordpress-reviews
* Add wordpress-version-notices
=> Add the missed libraries on lib/vendor

revisionary.php
Display an error message after allowing clean plugin activation.
#1061
=> Error activating free and pro plugins together

admin/options.php
=> Options screen has a div missing a closing tag

functions.php
=> Revision preview clears category / term changes

revisionary_main.php
=> Pro: Beaver Builder - Revision preview top bar not displayed after front end edit

front_rvy.php
=> PHP 8.1 - Warning for dynamic property creation in revision preview

admin/admin-init_rvy.php, admin/class-list-table-archive.php, admin/options.php, admin/revision-action_rvy.php, admin/revision-archive_rvy.php, defaults_rvy.php
=> Allow users to delete revisions from the Revision Archive

functions.php
=> Custom fields with multiple values stored to the same key were not revisioned correctly

front_rvy.php
=> Revision Archive preview does not display

rvy_init-functions.php
=> Scheduled Revision is not published under some configurations

admin/admin_rvy.php, admin/class-list-table-archive.php, admin/class-list-table_rvy.php
=> Screen Options on Queue, Archive to set pagination (Revisions per page)

rvy_init.php
=> Advanced Custom Fields: Fields not displayed in preview of submitted Revision

admin/revision-ui_rvy.php, front_rvy.php, revisionary_main.php, rvy_init-functions.php, rvy_init.php
=> Revision Preview of Home Page incorrect in some cases

admin/revision-action_rvy.php
=> Pro: Appoval of revision to Draft post should (optionally) set status to Published

rvy_init.php
=> Pagination setting changes not applied to Queue, Archive

admin/class-list-table-archive.php
=> Revision Archive: Paginination not applied unless Revision Deletion option is enabled

revisionary_main.php
=> PHP 8.2: Warning for dynamic property declaration

rvy_init.php
=> Pro: Cannot update revision or preview revision changes if ACF active

front_rvy.php
=> Revision preview styling breaks third party javascript on some installs

admin/edit-revision-ui_rvy.php, admin/rvy_revision-block-edit.dev.js, admin/rvy_revision-block-edit.js
=> WP 6.5: Date, Page Template UI hidden in Revision Editor

admin/edit-revision-classic-ui_rvy.php
=> Classic Editor: No Custom Fields metabox in Revision Editor

admin/admin-init_rvy.php
=> Revision Queue: Bulk Decline fails with "link expired" message

admin/edit-revision-ui_rvy.php
=> Revision Editor hides category selection checkboxes

revision-creation_rvy.php
=> New revisions could become orphaned from main post on WordPress VIP

revisionary-front.css
=> Review Preview top bar formatting broken by external CSS on some sites

front_rvy.php
=> Revision Preview top bar styling stuck in cache on some sites

admin/admin-init_rvy.php, admin/revision-action_rvy.php
=> Nonce failure on revision decline attempt

admin/admin-init_rvy.php
=> Nested Pages: Fatal error on Revision Queue bulk deletion

admin/post-editor-workflow-ui_rvy.php, revisionary_main.php
=> After revision creation in editor, Edit / Preview links susceptible to plugin conflicts

admin/admin-init_rvy.php
=> Revision Queue: After multiple bulk actions, confirmation notices are repeated

revisionary_main.php
=> Limit to One Revision: Fatal error on revision approval

admin/admin-init_rvy.php
=> Revision Queue: Decline link nonce failure

rvy_init.php
=> Revisions not submitted properly if ppma_edit_post_authors capability is assigned

includes/CoreAdmin.php
=> One error message was not translated

revisionary_main.php
=> After new revision creation in post editor, View / Edit links fail with PHP warnings

admin/rvy_revision-classic-edit.dev.js
=> Revision Classic Editor: Changing Featured Image doesn't disable Submit, Approve button

admin/rvy_revision-classic-edit.dev.js
=> Revision Classic Editor: Changing Category, Tag or other Meta box did not disable Approve button

utils.php
=> Block / Classic Editor usage incorrectly detected under some conditions

admin/class-list-table_rvy.php, admin/revision-queue_rvy.php
=> New action hook to support custom columns in Revision Queue table

admin/revision-action_rvy.php
=> WP Rocket: Clean post cache on revision publication

rvy_init-functions.php
=> Queue: Decline link fails

admin/rvy_post-block-edit.dev.js
=> "Schedule Revision" button captioning not applied with recent Gutenberg versions

admin/post-edit-block-ui_rvy.php, admin/rvy-revision-edit.css, admin/rvy_revision-block-edit.dev.js
=> Gutenberg 18.5: Revision UI not correctly displayed for revision edit

admin/class-list-table_rvy.php
=> PublishPress Permissions: Revision Queue listed some editable posts without edit link

rvy_init-functions.php
=> API : Modify revisionary_mail for headers customization

functions.php
Fixes #1307
The affected code is never executed by the plugin's own function calls.
=> Code errors in functions.php

admin/revision-action_rvy.php, revision-creation_rvy.php
=> Notifications not sent for auto-submitted revisions

functions.php
=> Error copying postmeta if null value is stored where array is expected

admin/revision-action_rvy.php
=> Revision approval in "publish by revision" mode publishes page without a URL

admin/edit-revision-classic-ui_rvy.php
=> Classic Editor: Revisors editing a revision cannot select a future date

admin/history_rvy.php
=> Revision History: PHP Warning for preg_replace parameter

admin/edit-revision-classic-ui_rvy.php
=> Duplicate revision creation on some sites

admin/options.php, defaults_rvy.php, rvy_init-functions.php
=> Setting to disable new unfiltered_html check

admin/admin-posts_rvy.php
=> New Revision link on Posts screen fails due to plugin conflict on some sites

admin/admin-posts_rvy.php, admin/options.php, defaults_rvy.php
Implement new plugin option "revision_limit_compat_mode"
Fixes #1359
=> Revision Creation excessively suppressed due to caching plugin conflict

admin/revisionary.css
=> Editor: Missing margin on Edit Revision button

languages/revisionary-es_ES.po, languages/revisionary-fr_FR.po, languages/revisionary-it_IT.po
=> Lang: ES, FR, IT

admin/admin-init_rvy.php
=> WP 6.7: Error for early loading of text domain on Revision bulk decline

admin/history_rvy.php
=> Revision read capabilities don't limit slider positions on Compare Revisions screen

admin/history_rvy.php
=> Security: Revisors could view other users' revisions inappropriately

admin/revision-action_rvy.php
=> Revision Restore: Warning for Undefined variable $scheduled

admin/revision-action_rvy.php
=> Page Parent revision not applied

admin/class-list-table-archive.php
=> Revision Archive: Incorrect time display for recent entries

admin/class-list-table-archive.php, admin/revision-action_rvy.php, functions.php
=> Revision Archive: Scheduled Revision approver not stored, displayed

admin/options.php, admin/revision-action_rvy.php, defaults_rvy.php
=> Revision Archive: Option to store custom fields from submitted / scheduled revisions

front_rvy.php
=> Preview bar: recaption Publish Now button

admin/options.php
=> Clarify a setting caption

revision-creation_rvy.php
https://github.com/publishpress/PublishPress-Revisions/pull/1388
=> createRevision() notification cleared suppress_redirects argument

admin/admin-posts_rvy.php
=> ACF Better Search: SQL error on Posts screen

admin/admin_rvy.php, admin/class-list-table_rvy.php, front_rvy.php, revisionary_main.php
=> Pro: Permissions compat mode not applied if Planner plugin inactive

admin/class-list-table_rvy.php
=> Revision Queue: Fatal error if Revision Submission is disabled

admin/history_rvy.php
=> Compare Revisions: Slider movement fails to reload comparison

front_rvy.php, rvy_init-functions.php
=> Preview of front page revision fails on some sites

admin/class-list-table_rvy.php
=> Revisors can't see own revisions in queue under some conditions

compat_rvy.php
=> Authors integration: Revisors cannot list own revision after updating it

admin/options.php
=> Settings: Clarify location of Compare Revisions features

admin/options.php
=> Settings > Queue captions

admin/options.php
=> Settings > Revision Captions

admin/admin-init_rvy.php
=> Bulk Delete causes fatal error

admin/admin-posts_rvy.php
=> Revision Queue: Database error with some third party plugins

revisionary_main.php
=> After Revision creation in editor, Edit link goes to Queue

functions.php
=> Revisions Compare: adjustment to support for a Pro feature

functions.php
=> Re-trigger fixDefaultNotificationsMetaKey()

functions.php, revision-creation_rvy.php
=> Pro: Planner Notifications for Revision Scheduling may be skipped

revisionary_main.php
=> Log users who have updated a revision

admin/admin_rvy.php
=> Use new Capabilities plugin filter to show capability descriptions

admin/rvy_post-block-edit.dev.js, admin/rvy_post-block-edit.js, admin/rvy_post-classic-edit.dev.js, admin/rvy_post-classic-edit.js
=> Post Editor: Remove "Preview Revision" button after revision creation

admin/options.php, admin/revisionary.css, common/css/pressshack-admin.css
=> Caption capability requirement options with link to PublishPress Capabilities screen

revisionary_main.php
=> Correct filtering of revision creation capability ("copy_post")

admin/admin_rvy.php
=> Add links below PublishPress Revisions description on Plugins screen

admin/admin_rvy.php
=> More links in Plugins row

functions.php
=> Plugin API: Add function publishpress_get_revision_info()

admin/revision-archive_rvy.php
=> PublishPress Authors: PHP warnings in Revision Archive

admin/class-list-table_rvy.php
Use the same display function as with other user name columns in this table.
=> Revision Queue: use get_the_author_meta('display_name') for Revised By column

admin/options.php, admin/revisionary.css, revisionary_main.php, submittee_rvy.php
Also consolidate Revision Creation, Submission, Scheduling options on a shared tab.
Also move Compare options to a dedicated tab.
#1027, #1028
=> Move Archive options to a dedicated tab; support new Archive options in Pro

admin/options.php
=> Adjust Settings hints to be less redundant, more clear and concise.

admin/admin_rvy.php
=> Pro: Remove "Display Branding" option

revisionary_main.php
Don't default-enable post types that don't have distinct post capabilities.
#1592
=> Enable New Revisions for fewer post types by default

admin/admin_rvy.php, admin/revisionary.css, includes/CoreAdmin.php
=> Better responsive styling for sidebar and top bar promo

admin/options.php, admin/revisionary.css, revisionary_main.php
=> Improve compatibility with private post types

admin/admin-posts_rvy.php
=> Revisors get PHP Warnings on Posts screen

admin/admin-posts_rvy.php
=> WooCommerce Products: No Edit links for Administrators and Editors

admin/admin-posts_rvy.php
=> CMS Tree Page View: JSON data output on Page Tree screen

admin/admin-posts_rvy.php
=> Other plugin's posts screen may output unformatted data

admin/admin_rvy.php, admin/options.php, admin/post-editor-workflow-ui_rvy.php, admin/revisionary.css, admin/rvy-revision-edit.css, admin/rvy_revision-block-edit.dev.js, admin/rvy_revision-classic-edit.dev.js
=> Show explanation, tool tip if Submit Revision button disabled

admin/post-edit-block-ui_rvy.php, admin/post-edit_rvy.php, admin/rvy_revision-block-edit.dev.js
=> Edit Revision: Don't disable submission buttons if Divi is active

front_rvy.php
=> Preview of Current Revision has trailing bullet after Edit link

admin/class-list-table-archive.php
=> Revision Archive bulk deletion checkboxes not displayed

admin/revision-action_rvy.php
=> Scheduled Revision publication fails if asynchronous setting enabled

admin/revision-action_rvy.php
=> Changes not displayed in Elementor Revision previews, approved Revisions

admin/revision-action_rvy.php
=> Incorrect redirect after approval of Elementor Revision

admin/options.php, admin/revisionary-settings.css
=> Contextual nudges on Settings screen

revisionary_main.php
=> Enable revision Permissions to override mange_unsubmitted_revisions capability check

admin/options.php
=> Move Pro tabs to the end

admin/options.php
=> Pro, not Premium

admin/admin-posts_rvy.php
=> Posts listing in admin doesn't show Has Revision caption if Enhanced access control enabled

admin/admin-posts_rvy.php
=> Some post types have non-functional edit links displayed to Revisors

admin/admin_rvy.php
=> Change some Revisions capability descriptions

lib/vendor/publishpress/wordpress-version-notices/src/Module/TopNotice/Module.php
The button color and text-decoration is incorrect in some library versions.
=> Ensure top banner button styling

admin/options.php, admin/post-editor-workflow-ui_rvy.php
=> Support extended captions on Approve button in Post Editor

admin/class-list-table_rvy.php
=> Clarify tool tip text for revisions submitted for a future publication date

admin/admin_rvy.php
=> Styling is not applied to elements on Revisions > Settings > License

admin/admin_rvy.php, admin/class-list-table_rvy.php, admin/history_rvy.php, admin/revision-ui_rvy.php
=> Fixed string translation

admin/options.php
=> Fatal error on Network Settings and Network Defaults screens

admin/options.php
=> Multisite: Plugin setting tabs are blank until a tab is clicked

functions.php, rvy_init-functions.php, submittee_rvy.php
=> Multisite: Compatibility Mode change leaves sub-site revisions with invalid post_status

front_rvy.php
=> Pro support: Elementor, Divi revision editor shows extra bullets in top bar

rvy_init-functions.php
=> Divi - no Save Draft, Preview buttons when editing Home Page revision

admin/revision-ui_rvy.php
Remove echo from esc_html_e() in revision-ui_rvy.php
=> Remove echo from esc_html_e() in revision-ui_rvy.php

admin/options.php
=> Use Thickbox frame for PublishPress Planner install link on Revisions > Settings

admin/admin-init_rvy.php, rvy_init-functions.php
=> Free plugin translations are not applied in Pro plugin

admin/history_rvy.php
=> Allow users to copy the content of a revision

admin/admin_rvy.php
=> Revisions of Custom Posts cannot be updated under some conditions

admin/edit-revision-classic-ui_rvy.php
=> Rank Math SEO - Update Revision button in Classic Editor fails on first click

admin/options.php, defaults_rvy.php, rvy_init.php
=> Plugin setting to disable Rank Math SEO for Revision editing

rvy_init-functions.php
=> Approve Revision button missing under some role configurations

admin/class-list-table_rvy.php, functions.php
=> Pro: Revision Statuses not properly displayed and filtered in Revision Queue
